### PR TITLE
fix: rewrite TabWidget handling

### LINKED ISSUE #17: mining event widget broken
Hypixels mining event widget in tab is missing a space in front of the content, this needs to be handled special

### PR DESCRIPTION
**Pull request by ItsEmpa**
Also adds some missing widgets, fixes the regex of some, improves unknown widget handling, adds more debug options for tab widgets, and an EnumArgument for commands

### CODE REVIEW

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/extentions/CollectionExtensions.kt [hunk 1]
```diff
@@ -28,6 +28,15 @@ inline fun <T> List<T>.peek(crossinline block: (T) -> Unit): List<T> {
     return this
 }
 
+fun <T> MutableIterable<T>.clearAnd(predicate: (T) -> Unit) {
+    val it = iterator()
+    while (it.hasNext()) {
+        predicate(it.next())
+        it.remove()
+        it.remove()
```
Comment (j10a1n15) [inline src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/extentions/CollectionExtensions.kt]: does this remove twice on purpose

**Review by j10a1n15 — CHANGES_REQUESTED** [review]
uhh enabling logging with stuff in it just crashes

java.lang.IllegalStateException: Unsupported type: Array
	at knot//tech.thatgravyboat.skyblockapi.utils.text.Text.join(Text.kt:45)
	at knot//tech.thatgravyboat.skyblockapi.utils.text.Text.join$default(Text.kt:36)
	at knot//tech.thatgravyboat.skyblockapi.impl.events.TabListEventHandler.onTabWidgetChange$lambda$11(TabListEventHandler.kt:224)
	at knot//tech.thatgravyboat.skyblockapi.utils.text.Text.debug$lambda$10(Text.kt:67)
	at knot//tech.thatgravyboat.skyblockapi.utils.text.Text.asComponent(Text.kt:31)
	at knot//tech.thatgravyboat.skyblockapi.utils.text.Text.of(Text.kt:27)
	at knot//tech.thatgravyboat.skyblockapi.utils.text.Text.debug$skyblock_api_versions1218(Text.kt:65)
	at knot//tech.thatgravyboat.skyblockapi.utils.text.Text.sendDebug$skyblock_api_versions1218(Text.kt:70)

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/impl/events/TabListEventHandler.kt [hunk 2]
```diff
@@ -152,4 +211,61 @@ object TabListEventHandler {
...
+            }
+            thenCallback("remove widget", EnumArgument<TabWidget>()) {
+                val widget = argument<TabWidget>("widget")!!
+                if (loggedWidgets.remove(widget)) {
+                    Text.sendDebug("Removed ${widget.name} from logged tab widgets.")
+                } else {
+                    Text.sendDebug("${widget.name} is not being logged.")
+                }
+            }
+            thenCallback("clear") {
```
Comment (j10a1n15) [inline src/common/main/kotlin/tech/thatgravyboat/skyblockapi/impl/events/TabListEventHandler.kt]:
```suggestion
            thenCallback("get widget", EnumArgument<TabWidget>()) {
                val widget = argument<TabWidget>("widget")!!
                widgets[widget]?.let {
                    Text.sendDebug("Contents of tab widget ${widget.name}") {
                        this.hover = Text.multiline(it)
                        onClick {
                            McClient.clipboard = it.joinToString("\n")
                            Text.sendDebug("Copied contents to clipboard.")
                        }
                    }
                } ?: Text.sendDebug("Tab widget ${widget.name} not present.")
            }
            thenCallback("clear") {
```

surely we can get this to test if it works 🙏

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/extentions/CollectionExtensions.kt (hunk 1 above)
Comment (ItsEmpa) [reply src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/extentions/CollectionExtensions.kt]: it is not

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/api/location/LocationAPI.kt [hunk 3]
```diff
@@ -83,8 +85,12 @@ object LocationAPI {
             }
         }
 
+    var lastWorldChange: Instant = Instant.DISTANT_PAST
```
Comment (ThatGravyBoat) [inline src/common/main/kotlin/tech/thatgravyboat/skyblockapi/api/location/LocationAPI.kt]:
```suggestion
    var lastServerChange: Instant = Instant.DISTANT_PAST
```

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/impl/events/TabListEventHandler.kt [hunk 4]
```diff
@@ -152,4 +211,74 @@ object TabListEventHandler {
...
+                        }
+                    }
+                } ?: Text.sendDebug("Tab widget ${widget.name} not present.")
+            }
+            thenCallback("clear") {
+                loggedWidgets.clear()
+                Text.sendDebug("Cleared logged tab widgets.")
+            }
+        }
+    }
```
Comment (ThatGravyBoat) [inline src/common/main/kotlin/tech/thatgravyboat/skyblockapi/impl/events/TabListEventHandler.kt]: put this in the debug package, this clutters this file too much

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/impl/events/TabListEventHandler.kt [hunk 5]
```diff
@@ -110,31 +126,74 @@ object TabListEventHandler {
...
+        val widgetLines = mutableMapOf<TabWidget, List<Component>>()
+        val currentComponents = mutableListOf<Component>()
+        var currentWidget: TabWidget? = null
+
+        fun flushWidget() {
+            if (currentWidget != null && currentComponents.isNotEmpty()) {
+                widgetLines[currentWidget!!] = currentComponents.toList()
+                currentComponents.clear()
+            }
+        }
```
Comment (ThatGravyBoat) [inline src/common/main/kotlin/tech/thatgravyboat/skyblockapi/impl/events/TabListEventHandler.kt:145]: not a fan of this inline function here

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/impl/events/TabListEventHandler.kt [hunk 6]
```diff
@@ -110,31 +126,74 @@ object TabListEventHandler {
...
+            if (widget == null) {
+                if (couldBeUnknownWidgetStart(currentWidget, stripped)) {
+                    handleUnknownWidget(stripped)
                 }
-                return@forEach
+                currentComponents.add(line)
+                continue
             }
+            flushWidget()
+            currentComponents.clear()
```
Comment (ThatGravyBoat) [inline src/common/main/kotlin/tech/thatgravyboat/skyblockapi/impl/events/TabListEventHandler.kt]: this is just done in flushWidget

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/impl/events/TabListEventHandler.kt [hunk 7]
```diff
@@ -110,31 +126,74 @@ object TabListEventHandler {
...
-            val new = section.map { it.stripped }
-            if (old != new) {
-                widgets[widget] = new
-                TabWidgetChangeEvent(widget, old, new, section).post()
+            val newStrings = new.map { it.stripped }
+            if (old != newStrings) {
+                widgets[widget] = newStrings
+                TabWidgetChangeEvent(widget, old, newStrings, new).post()
+            }
+        }
```
Comment (ThatGravyBoat) [inline src/common/main/kotlin/tech/thatgravyboat/skyblockapi/impl/events/TabListEventHandler.kt]: the second parameter should still be named section and the newStrings should be named back to new

**Review by ThatGravyBoat — CHANGES_REQUESTED** [review]

**Review by ThatGravyBoat — DISMISSED** [review]

**Review by j10a1n15 — DISMISSED** [review]

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/extentions/CollectionExtensions.kt [hunk 8]
```diff
@@ -28,6 +28,14 @@ inline fun <T> List<T>.peek(crossinline block: (T) -> Unit): List<T> {
     return this
 }
 
+fun <T> MutableIterable<T>.clearAnd(predicate: (T) -> Unit) {
```
Comment (meowora) [inline src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/extentions/CollectionExtensions.kt]: It's not a predicate 🥺

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/command/EnumArgument.kt [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+import com.mojang.brigadier.exceptions.DynamicCommandExceptionType
+import com.mojang.brigadier.suggestion.Suggestions
+import com.mojang.brigadier.suggestion.SuggestionsBuilder
+import tech.thatgravyboat.skyblockapi.utils.text.Text
+import tech.thatgravyboat.skyblockapi.utils.text.TextBuilder.append
+import tech.thatgravyboat.skyblockapi.utils.text.TextColor
+import tech.thatgravyboat.skyblockapi.utils.text.TextStyle.color
+import java.util.concurrent.CompletableFuture
+
+class EnumArgument<E : Enum<E>> private constructor(
```
Comment (meowora) [inline src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/command/EnumArgument.kt:15]: Don't we already have that?

Comment (meowora) [reply src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/command/EnumArgument.kt:15]: (might be mlib, in that case this one is fine)

**Review by meowora — CHANGES_REQUESTED** [review]

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/command/EnumArgument.kt (hunk 9 above)
Comment (ItsEmpa) [reply src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/command/EnumArgument.kt:15]: not in sbapi that i could see

Comment (j10a1n15) [reply src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/command/EnumArgument.kt:15]: https://github.com/meowdding/meowdding-lib/blob/d92d0887bc3f2ac0735ee1bd1480d63673e22935/src/main/kotlin/me/owdding/lib/utils/type/EnumArgumentType.kt#L17

Comment (ItsEmpa) [reply src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/command/EnumArgument.kt:15]: ah well, do i copy over the implementation to be the same one as the one in mlib then?

Comment (ThatGravyBoat) [reply src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/command/EnumArgument.kt:15]: your impl is fine

Comment (ItsEmpa) [reply src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/command/EnumArgument.kt:15]: yayy

File: src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/extentions/CollectionExtensions.kt (hunk 8 above)
Comment (ItsEmpa) [reply src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/extentions/CollectionExtensions.kt]: what would it be called then? just `block`?

Comment (meowora) [reply src/common/main/kotlin/tech/thatgravyboat/skyblockapi/utils/extentions/CollectionExtensions.kt]: action ig?

**Review by meowora — APPROVED** [review]

**Review by j10a1n15 — APPROVED** [review]

**Review by ThatGravyBoat — APPROVED** [review]
